[package]
name = "adventofcode-2023"
version = "0.1.0"
edition = "2021"

[dependencies]

[lints.clippy]
# Pedantic
pedantic = "warn"
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
# Nursery
nursery = "warn"
fallible_impl_from = "allow"